### PR TITLE
Fix test and adjust code

### PR DESCRIPTION
**Pull request by renatocarvalho**
This PR has several small tweaks and specially fixes the test code which was using the old breakpoints variables.

- Update comments on the code that were using the old variables names
- Adjust line spacing on some parts of the code
- Update .editorconfig
- Update packages and add licence to packge.json
- Update bower version
- Remove trailing spaces

@felics

### CODE REVIEW

**Comment by felics** [comment]
@renatocarvalho thank you so much for this!

**Comment by renatocarvalho** [comment]
@felics You're welcome! Don't you need to do another release?

**Comment by felics** [comment]
@renatocarvalho yup done. needed some beauty-sleep :lipstick:

**Comment by renatocarvalho** [comment]
@felics :smile:

**Pull request merged**
